server:
    port: 8080
spring:
    application:
      name: employee-service
    profiles:
      active: dev
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/employeesdatabase?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    
    config:
       import: "configserver:http://localhost:8090/"

# Test Details for Development Environment
#test:
#  details: Employee service details for development environment-0010
#  engineer: John Doe
#  department: Development Testing
#  engineerContact:
#    email: testengineer.dev@example.com
#    phone: 123-456-7890 

logging:
  level:
    web: DEBUG
    
    